### ISSUE TITLE
[Utils] bug in DataConversion::IntegerToBytes 

### ISSUE THREAD

**Issue by deepgully** [Zilliqa/Zilliqa#1542]
the right bit shift is undefined operation if SIZE >= sizeof(T). 

https://github.com/Zilliqa/Zilliqa/blob/5f9bc6620a04e46970b9c2e61ead5faa998a8db9/src/libUtils/DataConversion.h#L107-L116

`DataConversion::IntegerToBytes<uint32_t, UINT256_SIZE>(0x0001);` will generate reduplicated bytes.
`0x......0001.....0001......0001`

The correct bytes should be `0x0000............0001`

``` c++
  template <typename T, size_t SIZE>
  static bytes IntegerToBytes(T value) {
    bytes result(SIZE);
    std::fill(result.begin(), result.end(), 0x00);

    for (size_t i = 0; i < sizeof(T); i++) {
      result[SIZE - i - 1] = (value >> (i * 8));
    }
    return result;
  }
```

**Comment by ansnunez** [comment]
If `sizeof(T)` can be used to infer the size of `typename T`, then the `size_t SIZE` template parameter is actually unnecessary.  The reason why `SIZE` is there - and why we use `i < SIZE` instead of `i < sizeof(T)` - is because `sizeof()` does not work correctly for the `boost::multiprecision` types (see `Serializable::SetNumber` for a similar example).

Thus, if somehow `SIZE` is not set to a correct value, it is more of a usage problem than a code bug.
