### ISSUE TITLE
[BUG] GetPendingTxn doesn't work

### ISSUE THREAD

**Issue by bogdan** [Zilliqa/Zilliqa#2034]
### Issue 

GetPendingTxn can only return `Txn already processed and confirmed` or `Txn not pending` but never anything like `Txn is in the pool`.
So there is no way to distinguish if tx is in the pool or never seen.

### Steps to Reproduce

Here are 2 requests in my console. Believe it or not, there only 1 second apart:

```
$ curl -d '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetPendingTxn",
    "params": ["2aec279a5637739a031d20b19a76087e2911b4e37600b36f65a4db8f87ba5a2b"]
}' -H "Content-Type: application/json" -X POST "https://api.zilliqa.com/"

{"id":"1","jsonrpc":"2.0","result":{"code":0,"confirmed":false,"info":"Txn not pending"}}%     

$ curl -d '{
    "id": "1",
    "jsonrpc": "2.0",
    "method": "GetPendingTxn",
    "params": ["2aec279a5637739a031d20b19a76087e2911b4e37600b36f65a4db8f87ba5a2b"]
}' -H "Content-Type: application/json" -X POST "https://api.zilliqa.com/"

{"id":"1","jsonrpc":"2.0","result":{"code":0,"confirmed":true,"info":"Txn already processed and confirmed"}}%
```

#### Expected

I've expected to receive any kind of status that tx was in the pool. Maybe this one: https://github.com/Zilliqa/Zilliqa/blob/6a079f5d1db4d7b89aa4df7f926a7298a1bc9965/src/libServer/LookupServer.cpp#L1663
But it never came out. Tried multiple times with different txs.

#### Actual

No message indicating that tx is in the pool.

#### Impact:
- [ ] Critical
- [x] High
- [ ]  Medium
- [ ] Low

**Comment by ansnunez** [comment]
Hi @bogdan, how the pending txn pool works is that lookup nodes become aware a txn is pending only at the end of the Tx epoch in which the txn was dispatched by the particular lookup that processed your CreateTransaction request. The end of the Tx epoch is the time when the network (i.e., the shards) sends over the list of pending txns to all the lookups.

However, the end of the Tx epoch is also the time when the list of confirmed txns is sent over.

So, I believe what happened in your case is that a txn was both deployed by the lookup and confirmed by the network in the same Tx epoch where you made those two queries. This would explain why you see "Txn not pending" and then suddenly "Txn already processed and confirmed".

Should the txn be left unconfirmed after that Tx epoch, then you are correct that you should see something like "Transaction valid but consensus not reached". However, seeing this status message can depend on conditions such as timing, the volume of transactions, the gas limit for each Tx block, etc.

So in some sense you are right, GetPendingTxn doesn't work - or at least, it doesn't work immediately as you would have expected. It still has utility but given the limitations of its design we have some other work in the pipeline for getting more accurate txn statuses.

**Comment by bogdan** [comment]
@ansnunez, my problems is that I wasn't ever able to receive any other message than "Txn not pending" and "Txn already processed and confirmed". I put the example of 2 requests 1 second apart because I thought this is the most obvisous one. I can imagine that this whole system may give you such cases sometimes, but I tried many times with many Txs in different times of a day: no "Transaction valid but consensus not reached" ever seen.

Can you try it for yourself and get this case with your own transaction on mainnet?

**Comment by ansnunez** [comment]
@bogdan I tried it as well and get a similar result as yours (not pending then suddenly confirmed the next second). This is because the txn gets dispatched **and** confirmed in the same epoch.

If you really want to see other messages, we have to get all the conditions right to induce getting those other messages (by the way we've updated the [API documentation](https://apidocs.zilliqa.com/#getpendingtxn) to list those other messages).

For example:
- To get "Nonce too high" you would have to send a txn with a wrong nonce.
- To get "Could not fit in as microblock gas limit reached" the shard where your txn is deployed must be saturated with txn requests such that the gas limit is reached at the time your txn is processed.
- To get "Transaction valid but consensus not reached" the shard where your txn is deployed must have been excluded from consensus (e.g., txn processing timeout was reached).

So as you can see, `GetPendingTxn` right now is really more useful as a diagnostic tool than as a txn tracking tool (i.e., after 2 or more epochs from time of dispatch), because these status messages only appear in extraordinary circumstances.

I know this doesn't make the API that much more useful than `GetTransaction` for txn tracking, which is why eventually we'll be coming up with other more useful ways to get more visibility into the "real-time" location of your txn within the shard network.
