### ISSUE TITLE
Memory leakage after POW

### ISSUE THREAD

**Issue by ckyang** [Zilliqa/Zilliqa#310]
In current version, a regular memory leakage happened after POW.
Here is reproducing step:

1. Create 2 folders for lookup and normal
2. For lookup: ./build_lookup.sh; cd build_lookup; ./tests/Node/test_node_lookup.sh
3. For normal: ./build.sh; cd build; ./tests/Node/test_node_simple.sh
4. htop

The memory usage will dramatically increase about 300 ~ 500 MB every 5 tx epoch. (POW)

**Comment by ckyang** [comment]
@ansnunez Could you please take a look on this issue?
Thank you!

**Comment by ansnunez** [comment]
It seems like the problem is in the call to EthashConfigureLightClient inside DirectoryService::ProcessFinalBlockConsensusWhenDone.

Here are the steps to confirm this:

1. Set NUM_FINAL_BLOCK_PER_POW to 1 in constants_local.xml so that triggering POW happens faster.
2. Comment out the call to InitiatePoW1 inside Node::ProcessFinalBlock to cause the non-DS nodes to stall.
3. Run test_node_simple.sh and htop, and notice that the memory spike will still happen when you see the message "PoW needed" in a DS node's log.
4. Comment out the call to EthashConfigureLightClient inside DirectoryService::ProcessFinalBlockConsensusWhenDone.
5. Run test_node_simple.sh and htop, and notice that this time no memory spike occurs when you see the message "PoW needed" in a DS node's log.
6. Edit POW::EthashConfigureLightClient - Add sleep_for and log messages after EthashLightDelete and EthashLightNew.
7. Run test_node_simple.sh and htop, and notice that after the delete the memory doesn't go down and it actually goes further up after the new.

**Comment by ckyang** [comment]
There are 2 times of memory spike happened each epoch:

1. (200MB grow) Remove private key inside constants_local.xml (don't do txn) can avoid memory leak.

2. (150MB grow) Comment out the call to EthashConfigureLightClient inside DirectoryService::ProcessFinalBlockConsensusWhenDone can avoid memory leak.

Still need to find some way to fix above two memory leak.
