### ISSUE TITLE
build a docker container

### ISSUE THREAD

**Issue by bb111189** [Zilliqa/Zilliqa#51]

**Comment by Tails** [comment]
+1.

The difficulty is (I believe) that there is not a single endpoint to run Zilliqa right now, since a lot of test and internal functions are now still being used for the testnet. It would either need an entrypoint with multiple functions that can be called from a compose file, or multiple Dockerfiles.

**Comment by Gnnng** [comment]
It may also benefit the continuous integration. The project is mainly developed under Ubuntu 16.04 while the Travis CI only has native Ubuntu build environments for 12.04 and 14.04, which cause troubles when updating the dependencies. The developers need to maintain a separate set of dependency installation instructions in `.travis.yml` to pass the travis check. 

Since Travis CI support docker and we are rapidly developing things on Ubuntu 16.04, it would great if we could refrain from supporting previous Ubuntu versions shortly and simplify the developing, CI and testing process by only maintaining the 16.04 version.

Here are [examples](https://github.com/search?utf8=%E2%9C%93&q=docker%20pull%2016.04+filename%3A.travis.yml) of using Ubuntu 16.04 docker on Traivs CI.

**Comment by Gnnng** [comment]
The support for Ubuntu 16.04 travis build is added in #100.

**Comment by bb111189** [comment]
Closed. Community contributions has created the Dockerfile and it has been merged into the master branch.
