### ISSUE TITLE
Provide interface in P2PComm instead of repopulating the lookup into vector of Peer

### ISSUE THREAD

**Issue by ansnunez** [Zilliqa/Zilliqa#982]
As described in #953 Lookup.cpp

**Comment by jendis** [comment]
Please could you give me better idea what exactly should be done and what is the motivation for that in order to make it optimal?
From my current understanding, method P2PComm:SendBroadcastMessage(const vector<Peer>&, const bytes&) is supposed to be overloaded by P2PComm:SendBroadcastMessage(VectorOfLookupNode, const bytes&). But from my point of view, this brings no benefit since after calling lock_guard<mutex> lock(m_mutexLookupNodes)(that is necessary because of vector thread nonsafety), copy of member m_lookupNodes to new vector has to be done anyway. So this brings no performance gain and globally increases the number of lines.
Thank you for help.

**Comment by ansnunez** [comment]
#1279
